# Generated by Django 3.1.5 on 2021-06-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_setoran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petugas',
            name='cabang',
        ),
        migrations.AddField(
            model_name='petugas',
            name='namaunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setor.unit'),
        ),
    ]
