# Generated by Django 3.1.5 on 2021-07-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0003_auto_20210624_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penyetor',
            new_name='Peternak',
        ),
    ]
