# Generated by Django 3.1.5 on 2021-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0004_auto_20210712_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.IntegerField(null=True)),
            ],
        ),
    ]
