# Generated by Django 3.1.5 on 2021-07-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0009_auto_20210727_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='alamaunit',
            new_name='alamatunit',
        ),
    ]
