# Generated by Django 3.1.5 on 2021-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0010_auto_20210727_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peternak',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
