# Generated by Django 3.1.5 on 2021-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0012_peternak_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='peternak',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petugas',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
