# Generated by Django 3.1.5 on 2021-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0013_auto_20210817_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
