# Generated by Django 3.1.5 on 2021-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0015_auto_20210909_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setoran',
            name='tgl',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
